//
// Created by francisc on 12/4/24.
//

#ifndef CPPGAMEDARCUOPENGL_SQUARESTATE_HPP
#define CPPGAMEDARCUOPENGL_SQUARESTATE_HPP

enum SquareState{EMPTY, ALLY, ENEMY, WARZONE};

#endif //CPPGAMEDARCUOPENGL_SQUARESTATE_HPP
