
#ifndef CPPGAMEDARCUOPENGL_BULLETTYPES_HPP
#define CPPGAMEDARCUOPENGL_BULLETTYPES_HPP

enum BulletType{BASIC, SPREAD, ZIGZAG,
        FIRE, DNA, CHAOTIC,
        COCCI_BASIC, COCCI_STRONG,
        HEPYLORI_BASIC, HEPYLORI_STRONG,};

#endif //CPPGAMEDARCUOPENGL_BULLETTYPES_HPP
