
#ifndef CPPGAMEDARCUOPENGL_BULLETTYPES_HPP
#define CPPGAMEDARCUOPENGL_BULLETTYPES_HPP

enum BulletType{BASIC, SPREAD, ZIGZAG,
        FIRE, DNA, CHAOTIC,
        COCCI_BASIC, COCCI_STRONG,
        HEPYLORI_BASIC, HEPYLORI_STRONG,
        BAMBIR_BASIC, BAMBIR_STRONG, ALOOULA,
        BLOUT,
        HEPYLORI_BASIC, HEPYLORI_STRONG, TYNNA_SPECIAL, TARUS_ANTI_BAMBIRI};

#endif //CPPGAMEDARCUOPENGL_BULLETTYPES_HPP
