
#ifndef CPPGAMEDARCUOPENGL_DIRECTIONS_H
#define CPPGAMEDARCUOPENGL_DIRECTIONS_H

enum Directions: int {UP = 0b1000, DOWN = 0b0100, LEFT = 0b0010, RIGHT = 0b0001, NONE = 0};

#endif //CPPGAMEDARCUOPENGL_DIRECTIONS_H
