
#ifndef CPPGAMEDARCUOPENGL_GAMESTATES_H
#define CPPGAMEDARCUOPENGL_GAMESTATES_H

enum GameStates: int {WIN, LOSE, MAIN_MENU, LEVEL_MENU, EXIT, PLAY_1, PLAY_2, PLAY_3, PLAY_4, TEST};


#endif //CPPGAMEDARCUOPENGL_GAMESTATES_H
